version: "3"

services:
  anpv-build:
    image: qt6-build:latest-suse
    build:
      context: docker/
      dockerfile: Dockerfile-build.suse

  anpv:
    image: qt6-devel:latest-suse
    build:
      context: docker/
      dockerfile: Dockerfile-devel.suse
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - .:/anpv
      - /home:/home:ro
    network_mode: host
