version: "3"

services:
  anpv:
    image: qt6-kf6:latest
    build: docker/
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - .:/anpv
      - /home:/home:ro
    network_mode: host
